### ISSUE TITLE
19桁以降計算結果がおかしくなる問題について

### ISSUE THREAD

**Issue by code-raisan** [Riysan/Polygon-Inner-Angle#3]
![Screenshot_20201019_222257](https://user-images.githubusercontent.com/67790884/96456613-aab04480-1259-11eb-945f-c1a15bda5e6d.jpg)
原因がわかり次第修正します
(わかる方はプルリクを送って頂けると嬉しいです)

**Comment by kai0310** [comment]
@Riysan 
おそらく整数としての精度が保障されてないからかと。(未検証)
[Number.isSafeInteger()-MDN](https://developer.mozilla.org/ja/docs/Web/JavaScript/Reference/Global_Objects/Number/isSafeInteger)

解決策としてはBigInt型を使用するかバリデーションで防ぐなどの方法を検討してください。

**Comment by kai0310** [comment]
こっちの方が適切かな
[Number.MAX_SAFE_INTEGER - MDN](https://developer.mozilla.org/ja/docs/Web/JavaScript/Reference/Global_Objects/Number/MAX_SAFE_INTEGER)

**Comment by code-raisan** [comment]
なるほど、、ありがとうございます。

**Comment by code-raisan** [comment]
修正しました [pull #4 ](https://github.com/Riysan/Polygon-Inner-Angle/pull/4)
